name: Nighly Build MkDocs And Commit HTML

on:
  schedule:
    # Nightly at midnight PDT -- uses UTC, so 7am.
    - cron:  '0 7 * * *'
  # This lets us trigger manually from the UI.
  workflow_dispatch:

jobs:
  build:
    runs-on:
      labels: ubuntu-22.04-4core
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install mkdocs mkdocs-gen-files mkdocs-material mkdocs-exclude mkdocs-print-site-plugin mdx_truly_sane_lists
    - name: Build MkDocs And Commit HTML
      run: |
        mkdocs build
    - name: Upload static files as artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/
  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on:
      labels: ubuntu-22.04-4core
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4